tasks:
  - init: make
      curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
      mkdir -p /workspace/gcloud
      tar -C /workspace/gcloud -xvf /tmp/google-cloud-sdk.tar.gz 
      /workspace/gcloud/google-cloud-sdk/install.sh
      PATH $PATH:/workspace/gcloud/google-cloud-sdk/bin


# Downloading gcloud package
# RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz

# # Installing the package
# RUN mkdir -p /usr/local/gcloud \
#   && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
#   && /usr/local/gcloud/google-cloud-sdk/install.sh

# # Adding the package path to local
# ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin