apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcs
  labels:
    app: lcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lcs
  template:
    metadata:
      labels:
        app: lcs
    spec:
      containers:
      - name: lcs
        image: lcs:1
        imagePullPolicy: Never
        env:
        # Fix these to match your RabbitMQ configuration
        - name: BROKER_USER
          value: minikube
        - name: BROKER_PASSWORD
          value: verysecret
       #- name: BROKER_ADDRESS
       #  value: <rabbitmq>:5672
